id: AB75E416B
title: Short Maṇḍala Offering
type: translation
pechas:
- I7797772C
- IA7F3AC5C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:01.626692
  last_modified_at: 2023-01-04 12:35:01.626703
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I7797772C/8838: 7C4D
  IA7F3AC5C/936C: 7C4D
